/*
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Head over to utils/shopify.js to create your events and write your event functions in utils/events.
 * To update this file, run npm run update:config or bun run update:config.
 */

import crypto from "node:crypto";

/**
 * @param {import("@pracht/core").ApiRouteArgs}
 */
export default async function handler({ request }) {
  if (request.method !== "POST") {
    return new Response("It ain't POST mate.", { status: 400 });
  }

  const headers = Object.fromEntries(
    [...request.headers.entries()].map(([key, value]) => [
      key.toLowerCase(),
      value,
    ])
  );
  const topic = headers["shopify-topic"] || "";
  const shop = headers["shopify-shop-domain"] || "";
  const apiVersion = headers["shopify-api-version"] || "";
  const eventHandle = headers["shopify-handle"] || "";
  const eventId = headers["shopify-event-id"] || "";
  const rawBody = await request.clone().text();

  try {
    const generateHash = crypto
      .createHmac("SHA256", process.env.SHOPIFY_API_SECRET ?? "")
      .update(rawBody, "utf8")
      .digest("base64");

    const hmac = headers["shopify-hmac-sha256"] ?? "";
    const generatedBuffer = Buffer.from(generateHash);
    const hmacBuffer = Buffer.from(hmac);

    if (
      generatedBuffer.length !== hmacBuffer.length ||
      !crypto.timingSafeEqual(generatedBuffer, hmacBuffer)
    ) {
      return Response.json({ error: true }, { status: 400 });
    }

    //SWITCHCASE
    switch (eventHandle) {
      case "this-is-my-handle":
        await appUninstallHandler(
          topic,
          shop,
          rawBody,
          eventId,
          apiVersion,
          eventHandle
        );
        break;
      default:
        throw new Error(`Can't find a handler for ${eventHandle}`);
    }
    //SWITCHCASE END

    console.log(`--> Processed ${topic} from ${shop}`);
    return Response.json({ message: "ok" });
  } catch (e) {
    console.error(
      `---> Error while processing events for ${shop} at ${topic} | ${
        e instanceof Error ? e.message : String(e)
      }`
    );

    return Response.json({ message: "Error" }, { status: 500 });
  }
}
