import fs from "node:fs";
import path from "node:path";
import shopify from "../utils/shopify.js";

const eventWriter = (config) => {
  const events = shopify.user.events || [];
  if (!events.length) {
    writeToApi();
    return;
  }

  const handles = new Set();
  const subscriptions = events.map((event) => {
    if (handles.has(event.handle)) {
      throw new Error(`Duplicate event handle: ${event.handle}`);
    }
    handles.add(event.handle);

    const subscription = {
      topic: event.topic,
      actions: event.actions,
      uri: event.uri.startsWith("/api/events/")
        ? `${process.env.SHOPIFY_APP_URL}${event.uri}`
        : event.uri,
      handle: event.handle,
    };

    if (event.triggers) {
      subscription.triggers = event.triggers;
    }

    if (event.query) {
      subscription.query = event.query;
    }

    if (event.query_filter) {
      subscription.query_filter = event.query_filter;
    }

    return subscription;
  });

  config.events = {};
  config.events.api_version = "unstable";
  config.events.subscription = subscriptions;

  writeToApi();
};

const shopifyFilePath = path.join(process.cwd(), "utils", "shopify.js");
const eventsRouteFilePath = path.join(
  process.cwd(),
  "src",
  "api",
  "events",
  "*.js"
);

async function writeToApi() {
  try {
    const shopifyFileContent = fs.readFileSync(shopifyFilePath, "utf8");
    const eventImports = shopifyFileContent.match(
      /import .* from "\.\/events\/.*";/g
    );

    let eventsRouteFileContent = fs.readFileSync(eventsRouteFilePath, "utf8");
    const topComment = `/*
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Head over to utils/shopify.js to create your events and write your event functions in utils/events.
 * To update this file, run npm run update:config or bun run update:config.
 */\n\n`;

    eventsRouteFileContent = eventsRouteFileContent.replace(
      /\/\*[\s\S]*?\*\/\s*/,
      ""
    );

    let newFileContent = topComment + 'import crypto from "node:crypto";\n';

    if (eventImports) {
      for (const importStatement of eventImports) {
        newFileContent +=
          importStatement.replace("./events", "@/utils/events") + "\n";
      }
    }

    const mainContent = eventsRouteFileContent.replace(
      /^([\s\S]*?^import[^\n]*\n)+/m,
      ""
    );
    eventsRouteFileContent = newFileContent + mainContent;

    const events = shopify.user.events || [];
    let switchCaseStatement = "    switch (eventHandle) {\n";

    for (const entry of events) {
      if (!entry.uri.startsWith("/api/events")) continue;

      switchCaseStatement += `      case "${entry.handle}":\n`;
      switchCaseStatement += `        await ${entry.callback.name}(topic, shop, rawBody, eventId, apiVersion, eventHandle);\n`;
      switchCaseStatement += "        break;\n";
    }

    switchCaseStatement += "      default:\n";
    switchCaseStatement += `        throw new Error(\`Can't find a handler for \${eventHandle}\`);\n`;
    switchCaseStatement += "    }\n";

    eventsRouteFileContent = eventsRouteFileContent.replace(
      /\/\/SWITCHCASE\n[\s\S]*?\/\/SWITCHCASE END/,
      `//SWITCHCASE\n${switchCaseStatement}    //SWITCHCASE END`
    );

    fs.writeFileSync(eventsRouteFilePath, eventsRouteFileContent, "utf8");
  } catch (error) {
    console.error("Error writing to events route file:", error);
  }
}

export default eventWriter;
