import fs from "node:fs";
import path from "node:path";
import shopify from "../utils/shopify.js";

const webhookWriter = (config) => {
  const subscriptions = shopify.user.webhooks.map((webhook) => {
    const subscription = {
      topics: webhook.topics,
      uri: webhook.url.startsWith("/api/webhooks/")
        ? `${process.env.SHOPIFY_APP_URL}${webhook.url}`
        : webhook.url,
    };

    if (webhook.include_fields) {
      subscription.include_fields = webhook.include_fields;
    }

    if (webhook.filter) {
      subscription.filter = webhook.filter;
    }

    if (webhook.name) {
      subscription.name = webhook.name;
    }

    return subscription;
  });

  config.webhooks ??= {};
  config.webhooks.subscriptions = subscriptions;

  writeToApi().catch((error) => {
    console.error("Error writing to webhook route file:", error);
  });
};

const shopifyFilePath = path.join(process.cwd(), "utils", "shopify.js");
const webhookRouteFilePath = path.join(
  process.cwd(),
  "src",
  "api",
  "webhooks",
  "*.js"
);

async function writeToApi() {
  const shopifyFileContent = fs.readFileSync(shopifyFilePath, "utf8");
  const webhookImports = shopifyFileContent.match(
    /import .* from "\.\/webhooks\/.*";/g
  );

  let webhookRouteFileContent = fs.readFileSync(webhookRouteFilePath, "utf8");
  const topComment = `/*
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Head over to utils/shopify.js to create your webhooks and write your webhook functions in utils/webhooks.
 * To update this file, run npm run update:config or bun run update:config.
 */\n\n`;

  webhookRouteFileContent = webhookRouteFileContent.replace(
    /\/\*[\s\S]*?\*\/\s*/,
    ""
  );

  let newFileContent =
    topComment +
    'import crypto from "node:crypto";\n' +
    'import shopify from "@/utils/shopify";\n';

  if (webhookImports) {
    for (const importStatement of webhookImports) {
      newFileContent +=
        importStatement.replace("./webhooks", "@/utils/webhooks") + "\n";
    }
  }

  const mainContent = webhookRouteFileContent.replace(
    /^([\s\S]*?^import[^\n]*\n)+/m,
    ""
  );
  webhookRouteFileContent = newFileContent + mainContent;

  const hasDuplicateTopics = hasDuplicates(
    shopify.user.webhooks.flatMap((webhook) => webhook.topics)
  );
  const switchCaseStatement = buildSwitchCase(
    shopify.user.webhooks,
    hasDuplicateTopics
  );

  webhookRouteFileContent = webhookRouteFileContent.replace(
    /\/\/SWITCHCASE\n[\s\S]*?\/\/SWITCHCASE END/,
    `//SWITCHCASE\n${switchCaseStatement}//SWITCHCASE END`
  );

  fs.writeFileSync(webhookRouteFilePath, webhookRouteFileContent, "utf8");
}

function buildSwitchCase(webhooks, hasDuplicateTopics) {
  const matchExpression = hasDuplicateTopics
    ? "requestPath"
    : "normalizedTopic";
  let switchCaseStatement = `switch (${matchExpression}) {\n`;

  for (const entry of webhooks) {
    if (!entry.url.startsWith("/api/webhooks")) continue;

    const handlerName = entry.callback.name;
    if (hasDuplicateTopics) {
      switchCaseStatement += `  case "${entry.url}":\n`;
      switchCaseStatement += `    await ${handlerName}(normalizedTopic, shop, rawBody, webhookId, apiVersion);\n`;
      switchCaseStatement += "    break;\n";
      continue;
    }

    entry.topics.forEach((topic, index) => {
      switchCaseStatement += `  case "${toGraphqlTopic(topic)}":\n`;
      if (index === entry.topics.length - 1) {
        switchCaseStatement += `    await ${handlerName}(normalizedTopic, shop, rawBody, webhookId, apiVersion);\n`;
        switchCaseStatement += "    break;\n";
      }
    });
  }

  switchCaseStatement += "  default:\n";
  switchCaseStatement += `    throw new Error(\`Can't find a handler for \${topic || requestPath}\`);\n`;
  switchCaseStatement += "}\n";

  return switchCaseStatement;
}

function toGraphqlTopic(topic) {
  return topic.toUpperCase().replace(/[/.]/g, "_");
}

function hasDuplicates(values) {
  return new Set(values).size !== values.length;
}

export default webhookWriter;
