/*
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Head over to utils/shopify.js to create your webhooks and write your webhook functions in utils/webhooks.
 * To update this file, run npm run update:config or bun run update:config.
 */

import crypto from "node:crypto";
import shopify from "@/utils/shopify";
import appUninstallHandler from "@/utils/webhooks/app_uninstalled.js";

/**
 * @param {import("@pracht/core").ApiRouteArgs}
 */
export default async function handler({ request, url }) {
  if (request.method !== "POST") {
    return new Response("It ain't POST mate.", { status: 400 });
  }

  const headers = Object.fromEntries(
    [...request.headers.entries()].map(([key, value]) => [
      key.toLowerCase(),
      value,
    ])
  );
  const topic = headers["x-shopify-topic"] || "";
  const shop = headers["x-shopify-shop-domain"] || "";
  const apiVersion = headers["x-shopify-api-version"] || "";
  const webhookId = headers["x-shopify-webhook-id"] || "";
  const rawBody = await request.clone().text();
  const normalizedTopic = topic.toUpperCase().replace(/[/.]/g, "_");

  try {
    const generateHash = crypto
      .createHmac("SHA256", process.env.SHOPIFY_API_SECRET ?? "")
      .update(rawBody, "utf8")
      .digest("base64");

    if (
      !shopify.auth.safeCompare(
        generateHash,
        headers["x-shopify-hmac-sha256"] ?? ""
      )
    ) {
      return Response.json({ error: true }, { status: 400 });
    }

    const requestPath = url.pathname;

    //SWITCHCASE
    switch (normalizedTopic) {
      case "APP_UNINSTALLED":
        await appUninstallHandler(
          normalizedTopic,
          shop,
          rawBody,
          webhookId,
          apiVersion
        );
        break;
      default:
        throw new Error(`Can't find a handler for ${topic || requestPath}`);
    }
    //SWITCHCASE END

    console.log(`--> Processed ${topic} from ${shop}`);
    return Response.json({ message: "ok" });
  } catch (e) {
    console.error(
      `---> Error while processing webhooks for ${shop} at ${topic} | ${
        e instanceof Error ? e.message : String(e)
      }`
    );

    return Response.json({ message: "Error" }, { status: 500 });
  }
}
